### ISSUE TITLE
node-monitor crashes

### ISSUE THREAD

**Issue by hongkongkiwi** [lorenwest/node-monitor#24]
When I add this line:

`require('monitor').start();`

It gives me this stack error

```
monitor/node_modules/config/lib/config.js:1410
global.NODE_CONFIG.watchForConfigFileChanges();
                   ^
TypeError: Object [object Object] has no method 'watchForConfigFileChanges'
    at Object.<anonymous>        (/Users/andy/Development/javascript/rovio/node_modules/monitor/node_modules/config/lib/config.js:1410:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/andy/Development/javascript/rovio/node_modules/monitor/lib/Monitor.js:743:22
    at Object.<anonymous>     (/Users/andy/Development/javascript/rovio/node_modules/monitor/lib/Monitor.js:778:2)
    at Module._compile (module.js:456:26)
```

**Comment by lorenwest** [comment]
Hello Andy,

Apologies for the delayed response - just returned from vacation (without a computer!).

This appears to be the result of having a newer version of node-config in your path.  It is actually a problem with node-config (another package I wrote) vs. node-monitor.  Node-config should not be backwardly incompatible in this way, and I will make sure this issue is resolved before publishing this version of node-config to NPM.  You must have gotten a pre-release of node-config 1.0 directly from github vs. npm.

Thank you for catching this.  I will keep this issue open until it's resolved in node-config.

**Comment by lorenwest** [comment]
node-config v1.0.0 was published, resolving this issue.  Please let me know if you are experiencing this with the 1.0.0 version from npm.
