### ISSUE TITLE
deps._.out reference in stdout-logger.js fails on 0.4.2

### ISSUE THREAD

**Issue by ryanbreen** [lorenwest/node-monitor#4]
Apps that use monitor fail to start in 0.4.2 due to stdout-logger.js attempting to reference deps._.out on line 14:

deps._.out("stdout") in stdout

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object function (obj) { return new wrapper(obj); } has no method 'out'
    at Object.<anonymous> (/usr/local/lib/node/.npm/monitor/0.2.11/package/logger/stdout-logger.js:14:8)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at require (module.js:327:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/monitor/0.2.11/package/deps.js:29:18)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)

**Comment by ryanbreen** [comment]
Looks like this is some sort of NPM loading order issue.  Somehow it resolved for me by running 'npm test config' before running 'npm test monitor'.  Now monitor works fine.
